In [ ]:
## Numpy: It's a Python library used for fast mathematical operations on arrays and matrices.
## NumPy automatically performs element-wise operations. Without NumPy, you'd use normal Python lists: 
## NumPy automatically performs element-wise operations.
## Why do we use NumPy?
1. Arrays
2. Fast calculations
3. Statistics
4. Matrix operations
Useful in:
Machine Learning
Data Science
AI
Image Processing

5. Filtering data

In [2]:
import numpy as np

In [3]:
## create array using numpy
## create a 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)
## So in 1D arrays, shape tells you how many elements are present in each dimension.

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
arr2 = np.array([6,7,8,9,10])
arr2.reshape(1,5)  ## 1 row and 5 columns

array([[ 6,  7,  8,  9, 10]])

In [7]:
arr2 = np.array([[6,7,8,9,10]])
arr2.shape
## 2D → shape gives (rows, columns)

(1, 5)

In [9]:
## 2D Array
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [13]:
np.arange(0,10,2).reshape(5)

array([0, 2, 4, 6, 8])

In [14]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
## identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## Arributes of Numpy Array
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)                  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)    # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)              # Output: int64 (may vary by platform)
print("Item size (in bytes):", arr.itemsize) # Output: 8 (may vary by platform)

In [3]:
### Numpy Vectorized form
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Elememt Wise Addition
print("Addition:",arr1+arr2)
## Elememt Wise Substraction
print("Substraction:",arr1-arr2)

## Elememt Wise Multiplication
print("Multiplication:",arr1*arr2)
## Elememt Wise Division
print("Divison:",arr1/arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Divison: [0.1 0.1 0.1 0.1 0.1]


In [7]:
## Universal Function

##Square Root
arr = np.array([1,2,3,4,5])
print(np.sqrt(arr))

##Exponentional
print(np.exp(arr))

##Sine
print(np.sin(arr))

##Natural Log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [33]:
## Array slicing and Indexing 
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n" , arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [34]:
print(arr[0])
print(arr[0:2])  ## arr[row start: end row(not included)]


[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


In [35]:
arr[0][0]

np.int64(1)

In [36]:
arr[1:,2:] ##arr[row,column] : row = 1 (row 1 onwards) ; column = 2 (column 2 onwards)

array([[ 7,  8],
       [11, 12]])

In [37]:
## Ex : 2,3,4,6,7,8

print(arr[0:2,1:]) 

[[2 3 4]
 [6 7 8]]


In [38]:
## Ex: 6,7,10,11
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [39]:
## Modify Array Elements
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [40]:
arr[1]= [100,90,80,70]
print(arr)

[[100   2   3   4]
 [100  90  80  70]
 [  9  10  11  12]]


In [41]:
arr[1:]=10
print(arr)

[[100   2   3   4]
 [ 10  10  10  10]
 [ 10  10  10  10]]


In [46]:
## Statistical Concepts - Normalization
## to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

## Calculate the mean and Standard deviation
mean = np.mean(data)
std_dev = np.std(data)
print(mean)
print(std_dev)

## Normalise the data
normalised_data = (data - mean)/ std_dev
print("Normalised Data: " , normalised_data)

3.0
1.4142135623730951
Normalised Data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [47]:
import numpy as np

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [57]:
## Logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])

print(data>5)
print(data[data>5])
data[(data>=5) & (data<=8)]

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]


array([5, 6, 7, 8])

In [ ]:
## 3D → shape gives (matrices, rows, columns)